### ISSUE TITLE
DBC support?

### ISSUE THREAD

**Issue by brettgus** [diksm8/pGo-create#10]
Any plans to add deathbycaptcha support?

Captchas can be bought for as little as 1/10 of a cent on deathbycapctha.. would be awesome if we could use this.

Here's an example of deathbycaptcha API in Python
https://github.com/kanzure/python-deathbycaptcha

**Comment by MichalCerny** [comment]
I'm in .. buy 5k captcha for $6 run your script and I will pay you $5 for 100 accounts :) easy money
